import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0e0e0e",
  },
  topLogo: {
    flex: 1,
    width: null,
    height: null,
    resizeMode: "contain",
    marginHorizontal: 64,
    marginTop: -100,
  },
  bottomLogo: {
    flex: 1,
    width: null,
    height: null,
    resizeMode: "contain",
    marginHorizontal: 12,
    marginTop: -200,
  },
  middleLogo: {
    flex: 1,
    width: null,
    height: null,
    resizeMode: "contain",
    marginHorizontal: 42,
    marginTop: -280,
  },
  button: {
    backgroundColor: "white",
    width: "92%",
    alignSelf: "center",
    alignItems: "center",
    paddingVertical: 12,
    borderRadius: 16,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 64,
  },
  buttonText: {
    color: "#1a1a1a",
    fontWeight: 700,
    fontSize: 20,
  },
  radioGroup: {
    display: "flex",
    flexDirection: "row",
    margin: 8,
    width: "80%",
    marginLeft: "auto",
    marginRight: "auto",
  },
  radioBtn: {
    borderStyle: "solid",
    borderColor: "#000000",
    borderWidth: 3,
    margin: 4,
  },
  dropdownStyle: {
    backgroundColor: "#4b4b4b",
    width: 124,
    alignSelf: "flex-end",
    marginRight: "15%",
  },
  amountBoxStyle: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1a1a1a",
    width: "92%",
    alignSelf: "center",
    borderRadius: 16,
    marginBottom: 16,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  amountStyle: {
    fontWeight: 700,
    fontSize: 20,
    color: "white",
  },
  dropdownText: {
    fontWeight: 700,
    fontSize: 16,
    color: "white",
  },
});
